language: php

sudo: false

php:
  - 5.6
  - 7

matrix:
  fast_finish: true

# Cache Composer & Drush directories.
cache:
  bundler: true
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.drush/cache"

before_install:
  # Disable xdebug.
  - phpenv config-rm xdebug.ini
  # Update composer.
  - composer self-update
  - composer --version
  # Add the oauth token to prevent GitHub timeouts.
#  - git config --global github.accesstoken $GITHUB_OAUTH_TOKEN

install:
  # Add Composer's local bin directory to the PATH so that we will be running
  # our installed versions of Drush, PHPCS, Behat, PhantomJS, etc.
  - export PATH="$TRAVIS_BUILD_DIR/vendor/bin:$PATH"

  # Composer install should fail on bad patches.
  - export COMPOSER_EXIT_ON_PATCH_FAILURE=1

  # Let Composer do all the magic!
  - composer install
  - pwd
  - ls -lash
  - ls -lash vendor/

script:
  - mkdir $TRAVIS_BUILD_DIR/docroot/modules/contrib/akamai
  - rsync --exclude-from=$TRAVIS_BUILD_DIR/docroot $TRAVIS_BUILD_DIR/ $TRAVIS_BUILD_DIR/docroot/modules/contrib/akamai
  - cd $TRAVIS_BUILD_DIR/docroot/modules/contrib/akamai
  - phpcs $TRAVIS_BUILD_DIR/docroot/modules/contrib/akamai --standard=$TRAVIS_BUILD_DIR/vendor/drupal/coder/coder_sniffer/Drupal/ruleset.xml --ignore=bin,*.css,libraries,modules/contrib
  - cd $TRAVIS_BUILD_DIR/docroot
  - drush en akamai --yes
  # Renable xdebug for coverage tracking.
  - phpenv config-add /tmp/xdebug.ini
  - $TRAVIS_BUILD_DIR/vendor/bin/phpunit --coverage-text --bootstrap="$TRAVIS_BUILD_DIR/docroot/core/tests/bootstrap.php"
